// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cache-service/internal/biz"
	"cache-service/internal/conf"
	"cache-service/internal/data"
	"cache-service/internal/server"
	"cache-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	cacheRepo := data.NewCacheRepo(dataData, logger)
	cacheUsecase := biz.NewCacheUsecase(cacheRepo, logger)
	cacheService := service.NewCacheService(cacheUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, cacheService, logger)
	httpServer := server.NewHTTPServer(confServer, cacheService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
