version: '3.8'

services:
  # Jaeger服务
  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: jaeger
    ports:
      - "16686:16686"   # Jaeger UI
      - "14250:14250"   # gRPC
      - "14268:14268"   # HTTP
      - "6831:6831/udp" # UDP
      - "6832:6832/udp" # UDP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - jaeger-net

networks:
  jaeger-net:
    driver: bridge 